### ISSUE TITLE
Implement multiple rounds for reduction

### ISSUE THREAD

**Issue by tomwhite** [tomwhite/barry#1]
The `reduction` function can exceed the maximum memory allowed in some cases:

```
>>> import numpy as np
>>> import barry as xp
>>> spec = xp.Spec("tmp", max_mem=110)
>>> a = xp.ones((100, 10), dtype=np.uint8, chunks=(1, 10), spec=spec)
>>> xp.sum(a, axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tom/projects-workspace/barry/barry/array_api.py", line 161, in sum
    return reduction(x, np.sum, axis=axis, dtype=dtype, keepdims=keepdims)
  File "/Users/tom/projects-workspace/barry/barry/core.py", line 390, in reduction
    result = rechunk(result, target_chunks)
  File "/Users/tom/projects-workspace/barry/barry/core.py", line 342, in rechunk
    pipeline, target, required_mem, num_tasks = primitive_rechunk(
  File "/Users/tom/projects-workspace/barry/barry/primitive/rechunk.py", line 30, in rechunk
    copy_specs, intermediate, target = _setup_rechunk(
  File "/Users/tom/opt/miniconda3/envs/barry/lib/python3.8/site-packages/rechunker/api.py", line 472, in _setup_rechunk
    copy_spec = _setup_array_rechunk(
  File "/Users/tom/opt/miniconda3/envs/barry/lib/python3.8/site-packages/rechunker/api.py", line 531, in _setup_array_rechunk
    read_chunks, int_chunks, write_chunks = rechunking_plan(
  File "/Users/tom/opt/miniconda3/envs/barry/lib/python3.8/site-packages/rechunker/algorithm.py", line 124, in rechunking_plan
    raise ValueError(
ValueError: Target chunk memory (1000) exceeds max_mem (110)
```

The solution is to perform multiple rounds of reduction with chunks within the allowed memory size.

**Comment by tomwhite** [comment]
Fixed in 415918ef42a6e30a296e5d8a881469297a40d7fafor single axis case.
